version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - database
    env_file:
      - docker/.env.dev.database
      - docker/.env.dev.web

  database:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - docker/.env.dev.database

  tomcat:
    build:
      context: .
      dockerfile: Dockerfile-tomcat
    ports:
      - "8080:8080"
    depends_on:
      - database
    env_file:
      - docker/.env.dev.tomcat

volumes:
  db-data:
