version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    env_file:
      - docker/.env.dev.database
      - docker/.env.dev.web

  database:
    image: postgres
    env_file:
      - docker/.env.dev.database
    volumes:
      - db-data:/var/lib/postgresql/data

  tomcat:
    build:
      context: .
      dockerfile: Dockerfile-tomcat
    ports:
      - "8080:8080"


volumes:
  db-data:
