---
version: 2
jobs:
  build:
    working_directory: ~/ucsdlib/damspas
    parallelism: 3
    docker:
      - image: circleci/ruby:2.3.7-node
        environment:
          CIRCLE_ENV: test
          RAILS_ENV: test
          APPS_DHH_DEV_DB: localhost
          APPS_DHH_DEV_SOLR_URL: http://localhost:8080/solr/blacklight
          APPS_DHH_DEV_FEDORA_URL: http://localhost:8080/dams/fedora
          APPS_DHH_DEV_DB_USER: dams
          APPS_DHH_DEV_DB_PASS: dams
      - image: ucsdlib/docker-postgres-damsrepo
        environment:
          POSTGRES_USER: dams
          POSTGRES_PASSWORD: dams
      - image: ucsdlib/docker-tomcat-damsrepo
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -yqq --no-install-recommends libicu-dev && sudo apt-get clean
      - run: curl --output phantomjs https://s3.amazonaws.com/circle-support-bucket/phantomjs/phantomjs-2.0.1-linux-x86_64-dynamic
      - run: chmod a+x phantomjs
      - run:
          name: Make PhantomJS executable available on PATH
          command: |
            echo 'export PATH=$HOME/ucsdlib/damspas:$PATH' >> $BASH_ENV
            source ~/.bashrc
      - restore_cache:
          keys:
          # This branch if available
          - bundle-{{ "Gemfile" }}-{{ checksum "Gemfile.lock" }}
          - bundle- #fallback
      - run: bundle install --path vendor/bundle --jobs 4 --retry 3
      - save_cache:
          key: bundle-{{ "Gemfile" }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bundle exec rake db:setup
      - run:
          name: Run rspec in parallel
          command: |
            COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN bundle exec rspec --profile 10 \
                                                                         --format RspecJunitFormatter \
                                                                         --out test_results/rspec.xml \
                                                                         --format progress \
                                                                         $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      # Save test results
      - store_test_results:
          path: test_results
