defaults: &defaults
  host: <%= ENV.fetch('APPS_DHH_STAGING_SHARE_NOTIFY_HOST') {'share_host'}%>
  token: <%= ENV.fetch('APPS_DHH_STAGING_NOTIFY_TOKEN') {'share_token'}%>

development:
  <<: *defaults
  
pontos:
  <<: *defaults

gimili:
  <<: *defaults

staging:
  <<: *defaults

qa:
  <<: *defaults

demo:
  <<: *defaults

test:
  <<: *defaults

production:
  host: <%= ENV.fetch('APPS_DHH_PROD_SHARE_NOTIFY_HOST') {'share_host'}%>
  token: <%= ENV.fetch('APPS_DHH_PROD_SHARE_NOTIFY_TOKEN') {'share_token'}%>

